[build]
  # 构建命令 - 先进入frontend目录，安装依赖并构建
  command = "cd frontend && npm ci && npm run build"
  
  # 发布目录 - Vite默认构建输出到dist目录
  publish = "frontend/dist"

[build.environment]
  # Node.js版本
  NODE_VERSION = "18"
  # 使用npm作为包管理器
  NPM_USE_YARN = "false"

# SPA路由支持 - 所有路由都重定向到index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 安全头部设置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 静态资源缓存设置
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML文件缓存设置
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 开发预览设置
[context.deploy-preview]
  command = "cd frontend && npm ci && npm run build"

[context.branch-deploy]
  command = "cd frontend && npm ci && npm run build"